### ISSUE TITLE
Should LabelEncoder class have `inverse` as a parameter?

### ISSUE THREAD

**Issue by dnouri** [ottogroup/dstoolbox#34]
I'm using `PipelineY` with sklearn's `LabelEncoder` like so:

```python
    return PipelineY([...], y_transformer=LabelEncoder())
```

Firstly, does this seem reasonable?  If it does, then I think it would also make sense to have `Pipeline.predict` always use the inverse transform for `y`.  I'm trying to use a scorer with this pipeline, and it fails, because I can't pass kwargs to `predict` to the scorer.  I have to resort to creating my own scorer:

```python
def scorer(clf, X, y, score_func=accuracy_score):
    y_pred = clf.predict(X, inverse=True)
    return score_func(y, y_pred)
```

However, if `PipelineY` allowed me to specify `use_inverse_for_predict=True` or similar, at instantiation time, to signal that the behavior for `predict` should be to use the inverse transform by default, then I could go back to using sklearn's stock scorers.

**Comment by benjamin-work** [comment]
That's a reasonable requirement. Honestly I would drop the `inverse=True` parameter because of the reasons such as the one you mentioned.

I could change this, though probably not this week, but would also accept a PR :)

Interestingly, sklearn seems to have a similar feature in their pipeline:

https://github.com/scikit-learn/scikit-learn/blob/755c7dda3885e52c3439fc5a50903408d642bc58/sklearn/compose/_target.py#L17

I'm not sure whether this covers all the use cases of `PipelineY` but in general, it's probably better to de-couple the target transformation from the `Pipeline`.
