### ISSUE TITLE
ColumnTransformer and DataFrame

### ISSUE THREAD

**Issue by ashleygritzman** [ottogroup/dstoolbox#39]
It seems that the new(ish) ColumnTransformer class also has the problem that it doesn't return a DataFrame, are there any plans to add that to this library?

Alternatively, is anyone aware of a solution?

**Comment by benjamin-ny** [comment]
When dstoolbox was developed, there was basically no support in sklearn for working with DataFrames. Now there is `ColumnTransformer`, which provides similar functionality but in a different way (it mangles column selection with transformations, which dstoolbox doesn't). Tbh, I'm not really happy with `ColumnTransformer` and find the dstoolbox way more appealing but that's just my opinion.

Anyway, if you only wish to transform the output of `ColumnTransfromer` to a DataFrame, have a look at [`ToDataFrame`](https://github.com/ottogroup/dstoolbox/blob/84fad9eeac6c795436f3a8da8823a9a63a7234cd/dstoolbox/transformers/casting.py#L10). If you chain those two together in a `Pipeline`, it might solve your problem.

**Comment by ashleygritzman** [comment]
Thanks for the reply @benjamin-ny !

It seems that applying `ToDataFrame` after  `ColumnTransformer` does not preserve the names of the columns. This is a problem is my case, as I use the `ColumnTransformer` multiple times in my pipeline, and if I lose the column names then I can no longer select columns by name later in the pipeline, I can only select by column index (which obviously gets tricky to keep track of the exact order of columns).

Am I missing something? Or how would you recommend doing this?

**Comment by benjamin-ny** [comment]
There is no way to preserve the column names with this approach :/

First of all, the output of `ColumnTransformer` is just a numpy array, hence the column names are gone. Second of all, there is not necessarily a 1-1 mapping between column and output. E.g., say you apply a `OneHotEncoder` to a column, suddenly one column from your df results in 100 columns in your array, with no way of knowing before runtime how many columns you'll have.

Assume that you don't have the problem of dynamic number of columns: My suggestion would be to not use `ColumnTransformer` at all but instead rely in dstoolbox with individual subpipelines that pick individual columns using `ItemSelector`, apply transforms on them, and finally transform back to a df using `ToDataFrame`. You can bind those individual features together using `DataFrameFeatureUnion`.

[Here](https://nbviewer.jupyter.org/github/ottogroup/dstoolbox/blob/master/notebooks/Showcase.ipynb#Define-the-feature-transformation-step) is an example of how that could look like.

Maybe it would be possible to adjust the `ToDataFrame` class to allow for dynamic column names so that it could handle cases such as `OneHotEncoder`.

**Comment by ashleygritzman** [comment]
Ok thanks, I'll give that a try.

One related question on using `ItemSelector`: Let's say I'm using `ItemSelector` select and then transform a column called `address`, is there a way to add this column back to the main dataframe? This would be the equivalent of `remainder = 'passthough'` in `ColumnTransformer`.

One way I could do it is to select the `address` column with `ItemSelector`, then to drop the `address` column from the main dataframe, and then join them back together with `DataFrameFeatureUnion`. 

But I'm thinking that there must be an easier way?

**Comment by benjamin-ny** [comment]
Usually, I would give the new feature a new name, so that the old and the new feature are part of the concatenated df. Then later on, as a last step of the feature pipeline, you could use `ItemSelector` to only pick those columns you really need.

If you really want to replace the existing column (say, for memory reasons), there is no one step solution. My suggestion for this would be to use `DataFrameFeatureUnion` with `keep_original=False`; inside, you create two branches, one for your new feature and one that selects all columns _except_ the one you want to remove. To achieve the latter, `ItemSelector` allows to pass a callable as key, so e.g. `lambda col: col != "column-I-to-drop"` (or define a real function to not get into trouble with pickle).

I could see how having the option to specifically drop a column could be useful, maybe this could be added as a new feature.

**Comment by ashleygritzman** [comment]
Ok, with your inspiration I wrote a wrapper for `ItemSelector` that includes the remainder in the output.

```
class ItemSelectorWithRemainder(ItemSelector):
    def __init__(self, transformer, columns):
        self.selected_cols = columns
        self.transformer = transformer
        self.remainder_cols = None

    def fit(self, X, y=None):
        self.remainder_cols = self._remainder_cols(X.columns)
        self.transformer_with_remainder = DataFrameFeatureUnion([
            ('pipeline', Pipeline([('select', ItemSelector(self.selected_cols)),
                                   ('transformer', self.transformer)
                              ])),
            ('remainder', ItemSelector(list(self.remainder_cols)))
        ])
        self.transformer_with_remainder.fit(X, y)
        return self

    def transform(self, X, y=None):
        return self.transformer_with_remainder.transform(X) 
    
    def _remainder_cols(self, all_cols):
        self.remainder_cols = list(set(all_cols).difference(set(self.selected_cols)))
        return self.remainder_cols
```

**Comment by benjamin-ny** [comment]
Nice, I hope this works out for you now. If so, feel free to close the issue.
